config/routes.rb
Rails.application.routes.draw do
  resources :wish_lists
  resources :posts
  devise_for :users, controllers: { registrations: 'users/registrations', omniauth_callbacks: "users/omniauth_callbacks" }
  get 'home/index'
  get 'others_posts', to: 'posts#other_posts'
  post 'set_ratings', to: 'posts#set_ratings'

  root 'home#index'
end

app/models/wish_list.rb
class WishList < ApplicationRecord
    # belongs_to :user, class_name: "user"
    validates :location_name, presence: true
end

app/controllers/wish_lists_controller.rb
class WishListsController < ApplicationController
  before_action :set_wish_list, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /wish_lists
  # GET /wish_lists.json
  def index
    @wish_lists = WishList.where(user_id: current_user.id)
  end

  # GET /wish_lists/1
  # GET /wish_lists/1.json
  def show
  end

  # GET /wish_lists/new
  def new
    @wish_list = WishList.new
  end

  # GET /wish_lists/1/edit
  def edit
  end

  # POST /wish_lists
  # POST /wish_lists.json
  def create
    @wish_list = WishList.new(wish_list_params)
    puts params
    respond_to do |format|
      if @wish_list.save
        format.html { redirect_to @wish_list, notice: 'Wish list was successfully created.' }
        # format.json { render :show, status: :created, location: @wish_list }
      else
        format.html { render :new }
        # format.json { render json: @wish_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wish_lists/1
  # PATCH/PUT /wish_lists/1.json
  def update
    respond_to do |format|
      if @wish_list.update(wish_list_params)
        format.html { redirect_to @wish_list, notice: 'Wish list was successfully updated.' }
        # format.json { render :show, status: :ok, location: @wish_list }
      else
        format.html { render :edit }
        # format.json { render json: @wish_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wish_lists/1
  # DELETE /wish_lists/1.json
  def destroy
    @wish_list.destroy
    respond_to do |format|
      format.html { redirect_to wish_lists_url, notice: 'Wish list was successfully destroyed.' }
      # format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_wish_list
    @wish_list = WishList.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def wish_list_params
      params[:wish_list][:user_id] = current_user.id
    params.require(:wish_list).permit(:user_id, :location_name)
  end
end

app/helpers/wish_lists_helper.rb
module WishListsHelper
end

app/views/wish_lists/_form.html.erb
<%= form_with(model: wish_list, local: true) do |form| %>
  <% if wish_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(wish_list.errors.count, "error") %> prohibited this wish_list from being saved:</h2>

      <ul>
      <% wish_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :location_name %>
    <%= form.text_field :location_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/wish_lists/edit.html.erb
<h1>Editing Wish List</h1>




<!DOCTYPE html>
<html lang="en">
<head>
    <style>
        #box {
            background: #7FFF00
        }
    </style>
    <%= render partial: 'layouts/head' %> 
</head>
<body>
    <%= render partial: 'layouts/navbar' %>
        <section class="hero  is-fullheight">
            <div class="hero-body">
                <div class="container has-text-centered">
                    <div class="column is-half is-offset-3">
                        <div class="box" id = 'box'>
                            <h1>Edit Wish List</h1>
                            <%= render 'form', wish_list: @wish_list %>

                            <%= link_to 'Show', @wish_list %>
                            <%= link_to 'Back', wish_lists_path %>                      
                        </div>
                    </div>
                </div>
            </div>
        </section>
    <%= render partial: 'layouts/footer' %>
</body>
</html>

app/views/wish_lists/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <%= render partial: 'layouts/head' %>
    <style>
      h1 {
        text-align: center;
      }
    </style>
</head>
<body>
    <%= render partial: 'layouts/navbar' %>
       <div class="box">
         <div class="columns">
           <div class="column is-one-third"></div>
              <div class="column is-one-third">
                  <h1 class="is-large">Wish List</h1>
                  
                  <% @wish_lists.each do |wish_list| %>
                    <div class="card">
                      <div class="card-content">
                        <%= wish_list.user_id %>
                        <%= wish_list.location_name %>
                      </div>
                      <footer class="card-footer">
                        <%= link_to 'Edit Item', edit_wish_list_path(wish_list), class: 'card-footer-item' %>
                        <%= link_to 'Delete Item', wish_list, class: 'card-footer-item', method: :delete, data: { confirm: 'Are you sure?' } %>
                        <%= link_to 'Show', wish_list, class: 'card-footer-item' %>
                      </footer>
                    </div>
                  <% end %>
              </div>
           </div>
           <div class="column is-one-third"></div>
         </div>
       </div>
    <%= render partial: 'layouts/footer' %>
</body>
</html>

app/views/wish_lists/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <style>
        #box {
            background: #7FFF00
        }
    </style>
    <%= render partial: 'layouts/head' %> 
</head>
<body>
    <%= render partial: 'layouts/navbar' %>
        <section class="hero  is-fullheight">
            <div class="hero-body">
                <div class="container has-text-centered">
                    <div class="column is-half is-offset-3">
                        <div class="box" id = 'box'>
                            <h1>New Wish List</h1>
                            <%= render 'form', wish_list: @wish_list %>
                            <%= link_to 'Back', wish_lists_path %>                                
                        </div>
                    </div>
                </div>
            </div>
        </section>
    <%= render partial: 'layouts/footer' %>
</body>
</html>

app/views/wish_lists/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <%= render partial: 'layouts/head' %>
    <style>
      h1 {
        text-align: center;
      }
    </style>
</head>
<body>
    <%= render partial: 'layouts/navbar' %>
       <div class="box">
         <div class="columns">
           <div class="column is-one-third"></div>
              <div class="column is-one-third">
                  <h1 class="is-large">Wish List</h1>
                    <div class="card">
                      <div class="card-content">
                          <strong>Location name:</strong>
                          <%= @wish_list.location_name %>
                      </div>
                      <footer class="card-footer">
                        <%= link_to 'Edit Item', edit_wish_list_path(@wish_list), class: 'card-footer-item' %>
                        <%= link_to 'Back', wish_lists_path, class: 'card-footer-item' %>
                        <%= link_to 'Delete Item', @wish_list, class: 'card-footer-item', method: :delete, data: { confirm: 'Are you sure?' } %>
                        <%# link_to 'Show', wish_list %>
                      </footer>
                    </div>
              </div>
           </div>
           <div class="column is-one-third"></div>
         </div>
       </div>
    <%= render partial: 'layouts/footer' %>
</body>
</html>