config/routes.rb
Rails.application.routes.draw do
  resources :wish_lists
  resources :posts
  devise_for :users, controllers: { registrations: 'users/registrations', omniauth_callbacks: "users/omniauth_callbacks" }
  get 'home/index'
  get 'others_posts', to: 'posts#other_posts'
  post 'set_ratings', to: 'posts#set_ratings'

  root 'home#index'
end

app/models/post.rb
class Post < ApplicationRecord
  validates :description, :diary_type, :location, :user_id, presence: true
  # ---- below validations require "active_storage_validations" gem
  # ---- link ==> https://github.com/igorkasyanchuk/active_storage_validations
  # validates :picture, presence: true, content_type: ['image']
  enum diary_type: ['Within City', 'Out of City', 'Out of Country']

  has_many_attached :pictures
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :convert_post_id_to_integer, only: [:set_ratings]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.where(user_id: current_user.id)
  end

  def other_posts
    @posts = Post.where.not(user_id: current_user.id)
  end

  # GET /posts/1
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  def create
    puts params
    # redirect_to new_post_url
    @post = Post.new(post_params)
    # @post.picture.attach(params[:post][:picture])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        # format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, notice: 'Post not created successfully.' }
        # format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def set_ratings
    puts params
    check = PostRating.where(user_id: params[:user_id], post_id: params[:post_id])
    @post = Post.find_by(id: params[:post_id])

    if check.present?
      check.update(rating: params[:rating])
      redirect_to @post
    else
      rating = PostRating.new(append_ratings_params)
      respond_to do |format|
        if rating.save 
          format.html { redirect_to @post, notice: 'Rating Submitted' }
        else
          format.html { redirect_to @post, notice: 'Rating Not Submitted' }
        end
      end
    end 
  end

  private

    # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params[:post][:user_id] = current_user.id
    params.require(:post).permit(:description, :location, :ratings, :diary_type, :user_id, pictures: [])
  end

  def convert_post_id_to_integer 
    params[:user_id] = current_user.id
    params[:post_id] = params[:post_id].to_i
  end

  def append_ratings_params 
    params.permit(:user_id, :rating, :post_id)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.label :diary_type %>
    <%# form.number_field :diary_type  %>
    <%= form.select :diary_type, ["Within City", "Out of City", "Out of Country"] %>
  </div>

  <div class="field">
    <%= form.label :pictures %>
    <%= form.file_field :pictures, multiple: true %>
  </div>

  <div class="actions">
    <%= form.submit %>
    <%= link_to 'Back', posts_path %>
  </div>
<% end %>

app/views/posts/_show-image.html.erb
<div class= "card">
    <%= post.pictures.each do |picture| %>
        <div class="column">
        <div class="card-image">
            <figure class="image is-2by1">
            <!--<img src="<%= url_for(picture) %>%" alt="post picture">-->
                <%= image_tag picture %> 
            </figure>
        </div>
        </div>
    <% end %>          
    <div class="card-content">
        <p class="is-medium"><strong>Description: </strong> <%= post.description %> </p>  
        <p class="is-medium"><strong>Location:</strong> <%= post.location %> </p>  
        <p class="is-medium"><strong>Ratings:</strong> 
            <%# post.ratings %>
        </p> 
        <p><strong>Diary Type:</strong> <%= post.diary_type %> </p>
        <%= form_with(url: set_ratings_path, local: true) do |form| %>

            <div class="field">
                <%= form.label :rating %>
                <%= form.select :rating, [1, 2, 3, 4, 5] %>
                <%= form.hidden_field :post_id, value: params[:id]%>
            </div>

            <div class="actions">
                <%= form.submit %>
            </div>
        <% end %>
    </div>
    <footer class="card-footer">
        <%= link_to 'Back', posts_path, class: 'card-footer-item' %>
        <% if current_user.id == post.user_id %>
            <%= link_to 'Edit Post', edit_post_path(post), class: 'card-footer-item' %>
            <%= link_to 'Delete Post', post, method: :delete, data: { confirm: 'Are you sure?' }, class: 'card-footer-item' %>
        <% end %>
    </footer>
</div>

app/views/posts/edit.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <style>
        #box {
            background: #7FFF00
        }
    </style>
    <%= render partial: 'layouts/head' %> 
</head>
<body>
    <%= render partial: 'layouts/navbar' %>
        <section class="hero  is-fullheight">
            <div class="hero-body">
                <div class="container has-text-centered">
                    <div class="column is-half is-offset-3">
                        <div class="box" id = 'box'>
                            
                            <h3 class="subtitle has-text-grey">Edit Post</h3>
                            <%= render 'form', post: @post %>
                            <%= link_to 'Show', @post %>
                            <%= link_to 'Back', posts_path %>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    <%= render partial: 'layouts/footer' %>
</body>
</html>

app/views/posts/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <%= render partial: 'layouts/head' %>
  <style>
    .box {
      padding-top: 5px;
    }
    h1 {
      text-align: center;
      font-size: 30px;
      padding-bottom: 5px;
    }
  </style>
  
</head>
<body>
    <%= render partial: 'layouts/navbar' %>
  <div>
      <div class="box">
      <h1 class="title">Your Posts </h1>
          <% @posts.each_with_index do |post, index| %>
            <div class="columns">
              <%# if index == 0 or index % 3 == 0%>
              <div class="column is-one-third" id = "c1">  
                 <%# render partial: 'layouts/image-grid', locals: {post: post} %>
              </div>
              <%# elsif index % 3 == 1 %>
              <div class="column is-one-third" id = "c2">
                  <%= render partial: 'layouts/image-grid', locals: {post: post} %>
              </div>
              <%# elsif index % 3 == 2 %>
              <div class="column is-one-third" id = "c3">
               <%# render partial: 'layouts/image-grid', locals: {post: post} %>
              </div>
              <%# end %>
          </div>
        <% end %>
      </div>
  </div>
  
  <br>
  
  <% link_to 'New Post', new_post_path %>
  <%= render partial: 'layouts/footer' %>
</body>
</html>

app/views/posts/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <style>
        #box {
            background: #7FFF00
        }
    </style>
    <%= render partial: 'layouts/head' %> 
</head>
<body>
    <%= render partial: 'layouts/navbar' %>
        <section class="hero  is-fullheight">
            <div class="hero-body">
                <div class="container has-text-centered">
                    <div class="column is-half is-offset-3">
                        <div class="box" id = 'box'>
                            
                            <h3 class="subtitle has-text-grey">Upload Post</h3>
                            <%= render 'form', post: @post %>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    <%= render partial: 'layouts/footer' %>
</body>
</html>

app/views/posts/other_posts.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <%= render partial: 'layouts/head' %>
  <style>
    .box {
      padding-top: 5px;
    }
    h1 {
      text-align: center;
      font-size: 30px;
      padding-bottom: 5px;
    }
  </style>
</head>
<body>
    <%= render partial: 'layouts/navbar' %>
  <div>
      <div class="box">
      <h1 class="title">Others' Posts </h1>
          <% @posts.each do |post| %>
            <div class="columns">
              <div class="column"></div>
              <div class="column">
                <%= render partial: 'layouts/image-grid', locals: {post: post} %>
              </div>
              <div class="column"></div>
          </div>
        <% end %>
      </div>
  </div>
  <br>
  <%= render partial: 'layouts/footer' %>
</body>
</html>

app/views/posts/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <%= render partial: 'layouts/head' %>
  <script src='https://api.tiles.mapbox.com/mapbox-gl-js/v0.51.0/mapbox-gl.js'></script>
  <script src='https://unpkg.com/es6-promise@4.2.4/dist/es6-promise.auto.min.js'></script>
  <script src="https://unpkg.com/@mapbox/mapbox-sdk/umd/mapbox-sdk.min.js"></script>
  <link href='https://api.tiles.mapbox.com/mapbox-gl-js/v0.51.0/mapbox-gl.css' rel='stylesheet' />

  <style>
       #map { position: relative; top:0; bottom:0; width:100%; width: 300px; height: 500px; }
  </style>
</head>
<body>
    <%= render partial: 'layouts/navbar' %>
    <div class="box">
      <div class="columns">
        <div class="column is-one-third is-offset-2">
          <%= render partial: 'show-image', locals: {post: @post} %>
        </div>
        <div class="column is-one-third" > 
          <div id ="map"></div>
        </div>
      </div>
    </div>
    <script>
      mapboxgl.accessToken = 'pk.eyJ1IjoidGFtNTAxIiwiYSI6ImNqcGdleWFuMTBmaW4zd2xld2MyZTlmbncifQ.ZEBgLg7lBfTZrt207i8uJQ';

      var mapboxClient = mapboxSdk({ accessToken: mapboxgl.accessToken });
      mapboxClient.geocoding.forwardGeocode({
          query: '<%= @post.location %>',
          autocomplete: false,
          limit: 1
      }).send().then(function (response) {
            if (response && response.body && response.body.features && response.body.features.length) {
                var feature = response.body.features[0];

                var map = new mapboxgl.Map({
                    container: 'map',
                    style: 'mapbox://styles/mapbox/streets-v9',
                    center: feature.center,
                    zoom: 10
                });
                new mapboxgl.Marker()
                    .setLngLat(feature.center)
                    .addTo(map);
          }
        });
    </script>
    <%= render partial: 'layouts/footer' %>
</body>
</html>