config/routes.rb
Rails.application.routes.draw do
  resources :wish_lists
  resources :posts
  devise_for :users, controllers: { registrations: 'users/registrations', omniauth_callbacks: "users/omniauth_callbacks" }
  get 'home/index'
  get 'others_posts', to: 'posts#other_posts'
  post 'set_ratings', to: 'posts#set_ratings'

  root 'home#index'
end

app/views/layouts/_body.html.erb
<% unless current_user %>

<section class="hero  is-fullheight">
    <div class="hero-body">
        <div class="container">
            <div class="column is-half is-offset-3">
                <div class="has-text-grey has-text-centered">
                        <h1 class="title is-1 has-text-grey">Welcome to Trip Diary</h1>
                        <h2 class=" subtitle is-4 has-text-grey"> The best place to share your<br>awesome journey pitures with<br> others</h2>
                    </div>
            </div>
        </div>
    </div>
</section>
<% end %>

app/views/layouts/_footer.html.erb
<style>
    #footer {
        height: 5px;
    }
</style>

<footer id = "footer" class="footer footer-background-color">
        <div class="content has-text-centered ">
            <p>
            <b>Trip Diary</b> 
            is powered by Ruby on Rails, PostgreSql
            Heroku, Bulma.css & Github.
            </p>
        </div>
        <div class="content has-text-centered ">
            

            <a class="github-button" href="https://github.com/TAM360" data-size="large" aria-label="Follow @TAM360 on GitHub">Follow @TAM360</a>
        </div>
       </footer>   

app/views/layouts/_head.html.erb
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<title>Trip Diary</title>
<%= csrf_meta_tags %>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.1/css/bulma.min.css">
<script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
<!-- Place this tag in your head or just before your close body tag. -->
<script async defer src="https://buttons.github.io/buttons.js"></script>

app/views/layouts/_image-grid.html.erb
<div class= "card">
    <%= post.pictures.each do |picture| %>
        <div class="column">
        <div class="card-image">
            <figure class="image is-2by1">
            <!--<img src="<%= url_for(picture) %>%" alt="post picture">-->
                <%= image_tag picture %> 
            </figure>
        </div>
        </div>
    <% end %>          
    <div class="card-content">
        <p class="is-medium"><strong>Description: </strong> <%= post.description %> </p>  
        <p class="is-medium"><strong>Location:</strong> <%= post.location %> </p>  
        <p class="is-medium"><strong>Ratings:</strong> 
            <%# post.ratings %>
        </p> 
        <p><strong>Diary Type:</strong> <%= post.diary_type %> </p> 
        
    </div>
    <footer class="card-footer">
        <%= link_to 'Show Post', post, class: 'card-footer-item' %>
        <% if current_user.id == post.user_id %>
            <%= link_to 'Edit Post', edit_post_path(post), class: 'card-footer-item' %>
            <%= link_to 'Delete Post', post, method: :delete, data: { confirm: 'Are you sure?' }, class: 'card-footer-item' %>
        <% end %>
    </footer>
</div>

app/views/layouts/_navbar.html.erb
<%= stylesheet_link_tag 'application.css' %>
<nav id= "navbar" class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="#">
      <img src="http://travelobservers.com/wp-content/uploads/2017/03/Journi-app-icon.jpg" width="40" height="40">
    </a>

    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <p class="navbar-item">
        <b>Trip Diary</b>
      </p>
      <p class="navbar-item">
       <% if user_signed_in? %>
         <b><%= link_to current_user.user_name, root_path %></b>
       <% end%>
      
      <p class="navbar-item">
        <% if user_signed_in? %>
         <b><%= link_to 'Profile Edit', edit_user_registration_path %></b>
      <% end %>

      <p class="navbar-item">
          <% if user_signed_in? %>
          <b><%= link_to 'Your Posts', posts_path %></b>
      <% end %>
      
      <p class="navbar-item">
        <% if user_signed_in? %>
        <b><%= link_to "Other's Posts", others_posts_path %></b>
      <% end %>

      <p class="navbar-item">
          <% if user_signed_in? %>
          <b><%= link_to 'Upload New Post', new_post_path %></b>
      <% end %>
      </p>

      <p class="navbar-item">
        <% if user_signed_in? %>
          <b><%= link_to 'Wish List', wish_lists_path %></b>
        <% end %>
      </p>

      <p class="navbar-item">
        <% if user_signed_in? %>
          <b><%= link_to 'New Wish List', new_wish_list_path %></b>
        <% end %>
      </p>
    </div>
    </div>

    <div class="navbar-end">
      <div class="navbar-item">
    
        <p class="navbar-item">
        <% if user_signed_in? %>
          <b><%= link_to 'Log Out',destroy_user_session_path, method: :delete %></b>
        <% else %>
          <p class="navbar-item">
            <b><%= link_to 'Sign Up', new_user_registration_path %></b>
          </p>
          <b><%= link_to 'Login', new_user_session_path %></b>
        <% end %>
        </p> 
    </div>
  </div>
</nav>

app/views/layouts/_profile.html.erb
<% unless !current_user %>
<style>
        #box {background: #7FFF00}       
</style>
<section class="hero  is-fullheight">
    <div class="hero-body">
        <div class="container has-text-centered">
            <div class="column is-4 is-offset-4">
                <div class="box" id='box'>
                    <h3 class="title has-text-grey">
                        <p class="has-text-grey">Profile Information</p>
                        
                            <% if !current_user[:user_name].nil?%>
                                <p class='subtitle'>Username: &emsp;<%= current_user[:user_name]%></p>
                            <% end %>
                            <% if !current_user[:name].nil?%>
                                <p class='subtitle '>Full Name: &emsp;<%= current_user[:name]%></p>
                            <% end %>
                            <p class='subtitle '>Email: &emsp;<%= current_user[:email]%></p>
                            <p class='subtitle '>City: &emsp;<%= current_user[:city]%></p>
                            <p class='subtitle '>Country: &emsp;<%= current_user[:country]%></p>
                       
                </div>
            </div>
        </div>
    </div>
</section>
 <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TripDiary</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <!---
        <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    -->
    
    <%= yield %>
  </body>
</html>